# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e9acf24ecdccbc33e8a7d22bcc120f84d92a85cf7c97330fd5947718b5000f2f30239a9ccccc896da983aa444cb1dcaf31dc437823af20695bfdb471df85cb90

test:
  secret_key_base: c7b91fd3768e8e5963c9bff655e793f03c74cc757711fa5e7210d354721f2d2412f3d68d4dc056458003e4f08f438aeb83ffe7cdad3d3c86ccc9e92cfac8b397

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
